### PR TITLE
Tick version, rerendered if needed

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
This will fail until we have a build of `Cheroot`. (Ref. https://github.com/conda-forge/staged-recipes/pull/2612)

**Comment by jakirkham** [comment]
Now have `cheroot`. So this should be unblocked.

**Comment by jakirkham** [comment]
It appears to need `flup`.

**Comment by pmlandwehr** [comment]
Yeah - `flup` seems like it might take some work, so I was sitting on it for the moment.

**Comment by pmlandwehr** [comment]
Closing this, having inadvertently superceded it with a new pull. (https://github.com/conda-forge/cherrypy-feedstock/pull/10)

**Pull request closed without merging**
