### PR TITLE
bump to v17.3.0

### PR DESCRIPTION
**Pull request by carlodri**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`

* supersedes #43, #42, #41, #40.
* updates recipe with latest conda-forge practices

NOTE: added myself as maintainer

### CODE REVIEW

**Comment by carlodri** [comment]
Needs https://github.com/conda-forge/tempora-feedstock/pull/11 to fix build.

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge/core I think I need your help for this failing CI....

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by CJ-Wright** [comment]
I've asked it to rerun your build.

**Comment by carlodri** [comment]
@pmlandwehr this is ready to merge

**Comment by CJ-Wright** [comment]
Would you consider adding yourself to the recipe?

**Comment by carlodri** [comment]
I'm already there...! Thanks!

**Comment by carlodri** [comment]
@pmlandwehr, my usual, friendly ping....! Can you please review and merge?

**Comment by carlodri** [comment]
@pmlandwehr since I don't hear from you, I'm asking someone @conda-forge/core if they can kindly merge this...

**Comment by carlodri** [comment]
thanks @ocefpaf!

**Comment by ocefpaf** [comment]
No problem. It is always nice to get new maintainer for recipes with a single point of failure.

**Pull request merged**
