### PR TITLE
add windows console events support

### PR DESCRIPTION
**Pull request by carlodri**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

As per https://docs.cherrypy.org/en/latest/advanced.html#windows-console-events

Closes #39

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@jjhelmus @pmlandwehr let me know if you are ok with this change.

**Comment by jjhelmus** [comment]
It would be nice to cherrypick the updates to the about section from #39 (commit 92d272245902ec25350253f9f44e99ebad4829c6).  That should sync this recipe with the one in AnacondaRecipes.

**Comment by carlodri** [comment]
my very first cherry-pick 🎉, looks good!

**Pull request merged**
